[package]
name = "bevy_transitions"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.18"
bevy_color = "0.18"
bevy_ecs = "0.18"
bevy_picking = "0.18"
bevy_reflect = "0.18"
bevy_state = "0.18"
bevy_time = "0.18"
bevy_ui = "0.18"
derive-new = "0.7.0"

[dev-dependencies]
bevy = "0.18"
